---
- name: CIS Basic Hardening on Ubuntu
  hosts: localhost
  become: yes

  vars:
    login_banner: "Authorized users only. All actions are monitored."

  tasks:

    - name: Disable IP forwarding
      sysctl:
        name: "{{ item }}"
        value: '0'
        state: present
        sysctl_file: /etc/sysctl.conf
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding

    - name: Disable IPv6
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        sysctl_file: /etc/sysctl.conf
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6

    - name: Disable ICMP redirects (secure)
      sysctl:
        name: "{{ item }}"
        value: '0'
        state: present
        sysctl_file: /etc/sysctl.conf
      loop:
        - net.ipv4.conf.all.accept_redirects
        - net.ipv4.conf.default.accept_redirects
        - net.ipv4.conf.all.secure_redirects
        - net.ipv4.conf.default.secure_redirects

    - name: Apply sysctl changes
      command: sysctl -p

    - name: Set login warning banner
      copy:
        content: "{{ login_banner }}"
        dest: "{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - /etc/issue
        - /etc/issue.net

    - name: Ensure auditd is installed
      apt:
        name:
          - auditd
          - audispd-plugins
        state: present
        update_cache: yes

    - name: Add audit rule for login events
      copy:
        dest: /etc/audit/rules.d/cis-login.rules
        content: |
          -w /var/log/lastlog -p wa -k logins
          -w /var/run/faillock/ -p wa -k logins
        owner: root
        group: root
        mode: '0640'

    - name: Add audit rule for file deletion
      copy:
        dest: /etc/audit/rules.d/cis-delete.rules
        content: |
          -a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k delete
          -a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k delete
        owner: root
        group: root
        mode: '0640'

    - name: Restart auditd
      service:
        name: auditd
        state: restarted
        enabled: yes

    - name: Set password expiration to 90 days
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Ensure SSH LogLevel is set to INFO
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?LogLevel'
        line: 'LogLevel INFO'
        create: yes
        backrefs: yes

    - name: Restart SSH
      service:
        name: ssh
        state: restarted

